-- =========================================================
-- ONLINE ACADEMY MANAGEMENT SYSTEM (OAMS)
-- Advanced Queries File
-- =========================================================

USE oams;

-- =========================================================
-- Q1. Display all registered students
-- =========================================================

SELECT
    student_id,
    first_name,
    last_name,
    email,
    phone
FROM students;

-- =========================================================
-- Q2. Display all available courses with fee details
-- =========================================================

SELECT
    course_id,
    course_name,
    fee,
    duration_months,
    credit_hours
FROM courses
ORDER BY fee DESC;

-- =========================================================
-- Q3. Show all batches with course and instructor details
-- =========================================================

SELECT
    b.batch_id,
    b.batch_name,
    c.course_name,
    i.full_name AS instructor_name,
    b.schedule
FROM batches b
JOIN courses c
    ON b.course_id = c.course_id
JOIN instructors i
    ON b.instructor_id = i.instructor_id;

-- =========================================================
-- Q4. Display students enrolled in each batch
-- =========================================================

SELECT
    e.enrollment_id,
    s.first_name,
    s.last_name,
    b.batch_name,
    c.course_name
FROM enrollments e
JOIN students s
    ON e.student_id = s.student_id
JOIN batches b
    ON e.batch_id = b.batch_id
JOIN courses c
    ON b.course_id = c.course_id
ORDER BY b.batch_name;

-- =========================================================
-- Q5. Count total students enrolled in each course
-- =========================================================

SELECT
    c.course_name,
    COUNT(e.enrollment_id) AS total_students
FROM courses c
JOIN batches b
    ON c.course_id = b.course_id
JOIN enrollments e
    ON b.batch_id = e.batch_id
GROUP BY c.course_name
ORDER BY total_students DESC;

-- =========================================================
-- Q6. Find students with pending or partial payments
-- =========================================================

SELECT
    s.student_id,
    CONCAT(s.first_name, ' ', s.last_name) AS student_name,
    p.amount,
    p.payment_status
FROM students s
JOIN enrollments e
    ON s.student_id = e.student_id
JOIN payments p
    ON e.enrollment_id = p.enrollment_id
WHERE p.payment_status IN ('Pending', 'Partial');

-- =========================================================
-- Q7. Calculate total revenue generated by the academy
-- =========================================================

SELECT
    SUM(amount) AS total_revenue
FROM payments
WHERE payment_status = 'Paid';

-- =========================================================
-- Q8. Show instructor teaching workload
-- =========================================================

SELECT
    i.full_name AS instructor_name,
    COUNT(b.batch_id) AS total_batches
FROM instructors i
LEFT JOIN batches b
    ON i.instructor_id = b.instructor_id
GROUP BY i.instructor_id, i.full_name
ORDER BY total_batches DESC;

-- =========================================================
-- Q9. Find attendance percentage of each student
-- =========================================================

SELECT
    s.student_id,
    CONCAT(s.first_name, ' ', s.last_name) AS student_name,

    ROUND(
        (SUM(CASE
            WHEN a.attendance_status = 'Present' THEN 1
            ELSE 0
        END) * 100.0) / COUNT(a.attendance_id),
        2
    ) AS attendance_percentage

FROM students s
JOIN enrollments e
    ON s.student_id = e.student_id
JOIN attendance a
    ON e.enrollment_id = a.enrollment_id
GROUP BY s.student_id, student_name
ORDER BY attendance_percentage DESC;

-- =========================================================
-- Q10. Display students with attendance below 75%
-- =========================================================

SELECT
    s.student_id,
    CONCAT(s.first_name, ' ', s.last_name) AS student_name,

    ROUND(
        (SUM(CASE
            WHEN a.attendance_status = 'Present' THEN 1
            ELSE 0
        END) * 100.0) / COUNT(a.attendance_id),
        2
    ) AS attendance_percentage

FROM students s
JOIN enrollments e
    ON s.student_id = e.student_id
JOIN attendance a
    ON e.enrollment_id = a.enrollment_id
GROUP BY s.student_id, student_name
HAVING attendance_percentage < 75;

-- =========================================================
-- Q11. Show top 5 students based on marks obtained
-- =========================================================

SELECT
    s.student_id,
    CONCAT(s.first_name, ' ', s.last_name) AS student_name,
    AVG(r.marks_obtained) AS average_marks
FROM students s
JOIN results r
    ON s.student_id = r.student_id
GROUP BY s.student_id, student_name
ORDER BY average_marks DESC
LIMIT 5;

-- =========================================================
-- Q12. Display average marks for each exam
-- =========================================================

SELECT
    e.exam_title,
    AVG(r.marks_obtained) AS average_marks
FROM exams e
JOIN results r
    ON e.exam_id = r.exam_id
GROUP BY e.exam_title
ORDER BY average_marks DESC;

-- =========================================================
-- Q13. Find the most popular course based on enrollments
-- =========================================================

SELECT
    c.course_name,
    COUNT(en.enrollment_id) AS total_enrollments
FROM courses c
JOIN batches b
    ON c.course_id = b.course_id
JOIN enrollments en
    ON b.batch_id = en.batch_id
GROUP BY c.course_name
ORDER BY total_enrollments DESC
LIMIT 1;

-- =========================================================
-- Q14. Display batch generating highest revenue
-- =========================================================

SELECT
    b.batch_name,
    SUM(p.amount) AS total_revenue
FROM batches b
JOIN enrollments e
    ON b.batch_id = e.batch_id
JOIN payments p
    ON e.enrollment_id = p.enrollment_id
GROUP BY b.batch_name
ORDER BY total_revenue DESC
LIMIT 1;

-- =========================================================
-- Q15. Find students enrolled in multiple batches
-- =========================================================

SELECT
    s.student_id,
    CONCAT(s.first_name, ' ', s.last_name) AS student_name,
    COUNT(e.batch_id) AS total_batches
FROM students s
JOIN enrollments e
    ON s.student_id = e.student_id
GROUP BY s.student_id, student_name
HAVING COUNT(e.batch_id) > 1;

-- =========================================================
-- Q16. Show pass/fail ratio for each exam
-- =========================================================

SELECT
    ex.exam_title,

    SUM(CASE
        WHEN r.grade != 'F' THEN 1
        ELSE 0
    END) AS passed_students,

    SUM(CASE
        WHEN r.grade = 'F' THEN 1
        ELSE 0
    END) AS failed_students

FROM exams ex
JOIN results r
    ON ex.exam_id = r.exam_id
GROUP BY ex.exam_title;

-- =========================================================
-- Q17. Display monthly payment collection report
-- =========================================================

SELECT
    MONTH(payment_date) AS payment_month,
    YEAR(payment_date) AS payment_year,
    SUM(amount) AS monthly_collection
FROM payments
GROUP BY payment_year, payment_month
ORDER BY payment_year, payment_month;

-- =========================================================
-- Q18. Show complete result report of students
-- =========================================================

SELECT
    CONCAT(s.first_name, ' ', s.last_name) AS student_name,
    ex.exam_title,
    ex.exam_type,
    r.marks_obtained,
    r.grade
FROM results r
JOIN students s
    ON r.student_id = s.student_id
JOIN exams ex
    ON r.exam_id = ex.exam_id
ORDER BY student_name;

-- =========================================================
-- Q19. Find course materials uploaded for each batch
-- =========================================================

SELECT
    b.batch_name,
    cm.title,
    cm.file_type,
    cm.upload_date
FROM course_materials cm
JOIN batches b
    ON cm.batch_id = b.batch_id
ORDER BY b.batch_name;

-- =========================================================
-- Q20. Display complete payment history of students
-- =========================================================

SELECT
    CONCAT(s.first_name, ' ', s.last_name) AS student_name,
    c.course_name,
    p.amount,
    p.payment_method,
    p.payment_status,
    p.payment_date
FROM payments p
JOIN enrollments e
    ON p.enrollment_id = e.enrollment_id
JOIN students s
    ON e.student_id = s.student_id
JOIN batches b
    ON e.batch_id = b.batch_id
JOIN courses c
    ON b.course_id = c.course_id
ORDER BY p.payment_date;

-- =========================================================
-- END OF QUERIES FILE
-- =========================================================